In [1]:
import pandas as pd
import numpy as np

In [17]:
data = pd.read_csv('AAPL.csv',parse_dates=True)

In [18]:
data.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2020-12-04,122.599998,122.860001,121.519997,122.250000,121.500977,78260400
1,2020-12-07,122.309998,124.570000,122.250000,123.750000,122.991783,86712000
2,2020-12-08,124.370003,124.980003,123.089996,124.379997,123.617920,82225500
3,2020-12-09,124.529999,125.949997,121.000000,121.779999,121.033844,115089200
4,2020-12-10,120.500000,123.870003,120.150002,123.239998,122.484901,81312200

In [19]:
data.shape

(252, 7)

In [20]:
data['Date'] = pd.to_datetime(data['Date'],format="%Y-%m-%d")

In [21]:
data.isna().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [22]:
def createLagData(inpDf, numShift, colName):
    ldf = inpDf.copy()
    for i in range(numShift):
        ldf[colName+str(i+1)] = ldf[colName].shift(i+1)
    return(ldf)

In [23]:
data = data[['Date','Close']]

In [24]:
data.head()

        Date       Close
0 2020-12-04  122.250000
1 2020-12-07  123.750000
2 2020-12-08  124.379997
3 2020-12-09  121.779999
4 2020-12-10  123.239998

In [25]:
data = createLagData(data,60,'Close')

In [26]:
data.head()

,Date,Close,Close1,Close2,Close3,Close4,Close5,Close6,Close7,Close8,...,Close51,Close52,Close53,Close54,Close55,Close56,Close57,Close58,Close59,Close60
0,2020-12-04,122.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-12-07,123.750000,122.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-12-08,124.379997,123.750000,122.250000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-12-09,121.779999,124.379997,123.750000,122.25,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-12-10,123.239998,121.779999,124.379997,123.75,122.25,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
data.dropna(axis=0, inplace=True)

In [14]:
data.head()

,Date,Close,Close1,Close2,Close3,Close4,Close5,Close6,Close7,Close8,...,Close51,Close52,Close53,Close54,Close55,Close56,Close57,Close58,Close59,Close60
60,2021-03-04,120.129997,122.059998,125.120003,127.790001,121.260002,120.989998,125.349998,125.860001,126.000000,...,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998,121.779999,124.379997,123.750000,122.250000
61,2021-03-05,121.419998,120.129997,122.059998,125.120003,127.790001,121.260002,120.989998,125.349998,125.860001,...,126.660004,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998,121.779999,124.379997,123.750000
62,2021-03-08,116.360001,121.419998,120.129997,122.059998,125.120003,127.790001,121.260002,120.989998,125.349998,...,128.229996,126.660004,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998,121.779999,124.379997
63,2021-03-09,121.089996,116.360001,121.419998,120.129997,122.059998,125.120003,127.790001,121.260002,120.989998,...,131.880005,128.229996,126.660004,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998,121.779999
64,2021-03-10,119.980003,121.089996,116.360001,121.419998,120.129997,122.059998,125.120003,127.790001,121.260002,...,130.960007,131.880005,128.229996,126.660004,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998

In [15]:
data.shape

(192, 62)

In [16]:
data.tail()

,Date,Close,Close1,Close2,Close3,Close4,Close5,Close6,Close7,Close8,...,Close51,Close52,Close53,Close54,Close55,Close56,Close57,Close58,Close59,Close60
247,2021-11-29,160.240005,156.809998,161.940002,161.410004,161.020004,160.550003,157.869995,153.490005,151.000000,...,148.789993,149.029999,148.119995,149.550003,148.970001,154.070007,155.110001,156.690002,154.300003,153.649994
248,2021-11-30,165.300003,160.240005,156.809998,161.940002,161.410004,161.020004,160.550003,157.869995,153.490005,...,146.059998,148.789993,149.029999,148.119995,149.550003,148.970001,154.070007,155.110001,156.690002,154.300003
249,2021-12-01,164.770004,165.300003,160.240005,156.809998,161.940002,161.410004,161.020004,160.550003,157.869995,...,142.940002,146.059998,148.789993,149.029999,148.119995,149.550003,148.970001,154.070007,155.110001,156.690002
250,2021-12-02,163.759995,164.770004,165.300003,160.240005,156.809998,161.940002,161.410004,161.020004,160.550003,...,143.429993,142.940002,146.059998,148.789993,149.029999,148.119995,149.550003,148.970001,154.070007,155.110001
251,2021-12-03,161.839996,163.759995,164.770004,165.300003,160.240005,156.809998,161.940002,161.410004,161.020004,...,145.850006,143.429993,142.940002,146.059998,148.789993,149.029999,148.119995,149.550003,148.970001,154.070007

In [29]:
df_train = data.head(data.shape[0]-30)
df_test = data.tail(30)

In [30]:
X_train = df_train.drop(['Date','Close'],axis=1)
X_test =  df_test.drop(['Date','Close'],axis=1)

In [31]:
y_train = df_train['Close']
y_test = df_test['Close']

In [32]:
X_train.head()

,Close1,Close2,Close3,Close4,Close5,Close6,Close7,Close8,Close9,Close10,...,Close51,Close52,Close53,Close54,Close55,Close56,Close57,Close58,Close59,Close60
60,122.059998,125.120003,127.790001,121.260002,120.989998,125.349998,125.860001,126.000000,129.869995,129.710007,...,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998,121.779999,124.379997,123.750000,122.250000
61,120.129997,122.059998,125.120003,127.790001,121.260002,120.989998,125.349998,125.860001,126.000000,129.869995,...,126.660004,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998,121.779999,124.379997,123.750000
62,121.419998,120.129997,122.059998,125.120003,127.790001,121.260002,120.989998,125.349998,125.860001,126.000000,...,128.229996,126.660004,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998,121.779999,124.379997
63,116.360001,121.419998,120.129997,122.059998,125.120003,127.790001,121.260002,120.989998,125.349998,125.860001,...,131.880005,128.229996,126.660004,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998,121.779999
64,121.089996,116.360001,121.419998,120.129997,122.059998,125.120003,127.790001,121.260002,120.989998,125.349998,...,130.960007,131.880005,128.229996,126.660004,128.699997,127.809998,127.879997,121.779999,122.410004,123.239998

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

In [36]:
X_train_sc = np.reshape(X_train_sc, (X_train_sc.shape[0], X_train_sc.shape[1],1))

In [37]:
X_test_sc = np.reshape(X_test_sc, (X_test_sc.shape[0], X_test_sc.shape[1],1))

In [38]:
X_train_sc.shape

(162, 60, 1)

In [39]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense

In [40]:
rnn_model = Sequential()

In [41]:
rnn_model.add(LSTM(units=128, 
                   return_sequences=True, 
                   input_shape=(X_train_sc.shape[1],1)))
rnn_model.add(Dropout(0.2))

In [42]:
rnn_model.add(LSTM(units=64, return_sequences=True))
rnn_model.add(Dropout(0.2))

In [43]:
rnn_model.add(LSTM(units=32, return_sequences=True))
rnn_model.add(Dropout(0.2))

In [44]:
rnn_model.add(LSTM(units=16, return_sequences=False))
rnn_model.add(Dropout(0.2))

In [45]:
rnn_model.add(Dense(units = 1))

In [46]:
rnn_model.compile(optimizer='adam',
                  loss = 'mse',
                  metrics = [tf.keras.metrics.MeanAbsolutePercentageError()]
                 )

In [47]:
rnn_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm (LSTM)                  (None, 60, 128)           66560
_________________________________________________________________
dropout (Dropout)            (None, 60, 128)           0
_________________________________________________________________
lstm_1 (LSTM)                (None, 60, 64)            49408
_________________________________________________________________
dropout_1 (Dropout)          (None, 60, 64)            0
_________________________________________________________________
lstm_2 (LSTM)                (None, 60, 32)            12416
_________________________________________________________________
dropout_2 (Dropout)          (None, 60, 32)            0
_________________________________________________________________
lstm_3 (LSTM)                (None, 16)                3136
_________________________________________________________________
dropout_3 (Dropout)          (None, 16)                0
_________________________________________________________________
dense (Dense)                (None, 1)                 17
=================================================================
Total params: 131,537
Trainable params: 131,537
Non-trainable params: 0
_________________________________________________________________

In [49]:
rnn_model.fit(X_train_sc,y_train, validation_data = (X_test_sc, y_test),epochs=500, batch_size = 32)

Epoch 1/500
6/6 [==============================] - 1s 131ms/step - loss: 12498.9277 - mean_absolute_percentage_error: 81.1733 - val_loss: 16643.3008 - val_mean_absolute_percentage_error: 83.5281
Epoch 2/500
6/6 [==============================] - 1s 133ms/step - loss: 12515.5898 - mean_absolute_percentage_error: 81.2791 - val_loss: 16619.1172 - val_mean_absolute_percentage_error: 83.4672
Epoch 3/500
6/6 [==============================] - 1s 137ms/step - loss: 12518.4170 - mean_absolute_percentage_error: 81.2620 - val_loss: 16594.9512 - val_mean_absolute_percentage_error: 83.4062
Epoch 4/500
6/6 [==============================] - 1s 135ms/step - loss: 12495.6846 - mean_absolute_percentage_error: 81.1658 - val_loss: 16570.7148 - val_mean_absolute_percentage_error: 83.3451
Epoch 5/500
6/6 [==============================] - 1s 132ms/step - loss: 12451.5352 - mean_absolute_percentage_error: 80.9829 - val_loss: 16546.2930 - val_mean_absolute_percentage_error: 83.2834
Epoch 6/500
6/6 [==============================] - 1s 133ms/step - loss: 12407.5605 - mean_absolute_percentage_error: 80.8820 - val_loss: 16521.8184 - val_mean_absolute_percentage_error: 83.2216
Epoch 7/500
6/6 [==============================] - 1s 132ms/step - loss: 12471.6836 - mean_absolute_percentage_error: 81.0858 - val_loss: 16497.3438 - val_mean_absolute_percentage_error: 83.1597
Epoch 8/500
6/6 [==============================] - 1s 133ms/step - loss: 12344.4131 - mean_absolute_percentage_error: 80.6563 - val_loss: 16472.7246 - val_mean_absolute_percentage_error: 83.0974
Epoch 9/500
6/6 [==============================] - 1s 135ms/step - loss: 12364.3721 - mean_absolute_percentage_error: 80.7266 - val_loss: 16448.0742 - val_mean_absolute_percentage_error: 83.0350
Epoch 10/500
6/6 [==============================] - 1s 132ms/step - loss: 12402.3545 - mean_absolute_percentage_error: 80.8706 - val_loss: 16423.6309 - val_mean_absolute_percentage_error: 82.9730
Epoch 11/500
6/6 [==============================] - 1s 135ms/step - loss: 12301.8877 - mean_absolute_percentage_error: 80.5159 - val_loss: 16399.3066 - val_mean_absolute_percentage_error: 82.9113
Epoch 12/500
6/6 [==============================] - 1s 130ms/step - loss: 12349.3223 - mean_absolute_percentage_error: 80.6346 - val_loss: 16374.9287 - val_mean_absolute_percentage_error: 82.8494
Epoch 13/500
6/6 [==============================] - 1s 147ms/step - loss: 12297.3623 - mean_absolute_percentage_error: 80.5110 - val_loss: 16350.5479 - val_mean_absolute_percentage_error: 82.7875
Epoch 14/500
6/6 [==============================] - 1s 136ms/step - loss: 12247.9688 - mean_absolute_percentage_error: 80.3726 - val_loss: 16326.2402 - val_mean_absolute_percentage_error: 82.7257
Epoch 15/500
6/6 [==============================] - 1s 135ms/step - loss: 12277.3984 - mean_absolute_percentage_error: 80.4311 - val_loss: 16302.2295 - val_mean_absolute_percentage_error: 82.6646
Epoch 16/500
6/6 [==============================] - 1s 140ms/step - loss: 12252.6123 - mean_absolute_percentage_error: 80.3707 - val_loss: 16278.3086 - val_mean_absolute_percentage_error: 82.6037
Epoch 17/500
6/6 [==============================] - 1s 131ms/step - loss: 12159.6191 - mean_absolute_percentage_error: 80.0769 - val_loss: 16254.2959 - val_mean_absolute_percentage_error: 82.5426
Epoch 18/500
6/6 [==============================] - 1s 134ms/step - loss: 12183.4980 - mean_absolute_percentage_error: 80.1685 - val_loss: 16230.2002 - val_mean_absolute_percentage_error: 82.4811
Epoch 19/500
6/6 [==============================] - 1s 131ms/step - loss: 12206.7871 - mean_absolute_percentage_error: 80.1678 - val_loss: 16206.0869 - val_mean_absolute_percentage_error: 82.4196
Epoch 20/500
6/6 [==============================] - 1s 135ms/step - loss: 12135.8428 - mean_absolute_percentage_error: 79.9591 - val_loss: 16181.8184 - val_mean_absolute_percentage_error: 82.3577
Epoch 21/500
6/6 [==============================] - 1s 134ms/step - loss: 12167.2783 - mean_absolute_percentage_error: 80.0517 - val_loss: 16157.4150 - val_mean_absolute_percentage_error: 82.2953
Epoch 22/500
6/6 [==============================] - 1s 136ms/step - loss: 12116.8535 - mean_absolute_percentage_error: 79.9371 - val_loss: 16133.3330 - val_mean_absolute_percentage_error: 82.2337
Epoch 23/500
6/6 [==============================] - 1s 151ms/step - loss: 12047.6084 - mean_absolute_percentage_error: 79.7240 - val_loss: 16109.2334 - val_mean_absolute_percentage_error: 82.1720
Epoch 24/500
6/6 [==============================] - 1s 158ms/step - loss: 12024.8350 - mean_absolute_percentage_error: 79.5943 - val_loss: 16085.2666 - val_mean_absolute_percentage_error: 82.1107
Epoch 25/500
6/6 [==============================] - 1s 153ms/step - loss: 12024.1816 - mean_absolute_percentage_error: 79.6456 - val_loss: 16061.2373 - val_mean_absolute_percentage_error: 82.0491
Epoch 26/500
6/6 [==============================] - 1s 150ms/step - loss: 12069.6338 - mean_absolute_percentage_error: 79.7350 - val_loss: 16037.4023 - val_mean_absolute_percentage_error: 81.9879
Epoch 27/500
6/6 [==============================] - 1s 152ms/step - loss: 11973.5332 - mean_absolute_percentage_error: 79.4265 - val_loss: 16013.9111 - val_mean_absolute_percentage_error: 81.9277
Epoch 28/500
6/6 [==============================] - 1s 175ms/step - loss: 12083.8467 - mean_absolute_percentage_error: 79.7424 - val_loss: 15990.5732 - val_mean_absolute_percentage_error: 81.8677
Epoch 29/500
6/6 [==============================] - 1s 190ms/step - loss: 12040.5156 - mean_absolute_percentage_error: 79.6679 - val_loss: 15967.0781 - val_mean_absolute_percentage_error: 81.8073
Epoch 30/500
6/6 [==============================] - 1s 166ms/step - loss: 12127.8066 - mean_absolute_percentage_error: 79.8979 - val_loss: 15943.4521 - val_mean_absolute_percentage_error: 81.7466
Epoch 31/500
6/6 [==============================] - 1s 153ms/step - loss: 11813.2139 - mean_absolute_percentage_error: 78.9156 - val_loss: 15919.6562 - val_mean_absolute_percentage_error: 81.6853
Epoch 32/500
6/6 [==============================] - 1s 152ms/step - loss: 11977.8584 - mean_absolute_percentage_error: 79.4860 - val_loss: 15896.0254 - val_mean_absolute_percentage_error: 81.6244
Epoch 33/500
6/6 [==============================] - 1s 160ms/step - loss: 11959.9824 - mean_absolute_percentage_error: 79.3559 - val_loss: 15872.4932 - val_mean_absolute_percentage_error: 81.5637
Epoch 34/500
6/6 [==============================] - 1s 159ms/step - loss: 11819.7334 - mean_absolute_percentage_error: 78.9104 - val_loss: 15849.0713 - val_mean_absolute_percentage_error: 81.5033
Epoch 35/500
6/6 [==============================] - 1s 155ms/step - loss: 11925.2188 - mean_absolute_percentage_error: 79.3298 - val_loss: 15825.4395 - val_mean_absolute_percentage_error: 81.4423
Epoch 36/500
6/6 [==============================] - 1s 152ms/step - loss: 11827.8457 - mean_absolute_percentage_error: 78.9438 - val_loss: 15801.7275 - val_mean_absolute_percentage_error: 81.3810
Epoch 37/500
6/6 [==============================] - 1s 155ms/step - loss: 11717.1377 - mean_absolute_percentage_error: 78.5334 - val_loss: 15778.0225 - val_mean_absolute_percentage_error: 81.3197
Epoch 38/500
6/6 [==============================] - 1s 153ms/step - loss: 11745.9111 - mean_absolute_percentage_error: 78.6269 - val_loss: 15754.2373 - val_mean_absolute_percentage_error: 81.2582
Epoch 39/500
6/6 [==============================] - 1s 159ms/step - loss: 11832.3975 - mean_absolute_percentage_error: 78.9187 - val_loss: 15730.7373 - val_mean_absolute_percentage_error: 81.1973
Epoch 40/500
6/6 [==============================] - 1s 161ms/step - loss: 11732.6592 - mean_absolute_percentage_error: 78.6001 - val_loss: 15707.3066 - val_mean_absolute_percentage_error: 81.1366
Epoch 41/500
6/6 [==============================] - 1s 156ms/step - loss: 11695.8271 - mean_absolute_percentage_error: 78.4788 - val_loss: 15683.8193 - val_mean_absolute_percentage_error: 81.0757
Epoch 42/500
6/6 [==============================] - 1s 152ms/step - loss: 11803.9834 - mean_absolute_percentage_error: 78.8460 - val_loss: 15660.1826 - val_mean_absolute_percentage_error: 81.0143
Epoch 43/500
6/6 [==============================] - 1s 151ms/step - loss: 11729.5273 - mean_absolute_percentage_error: 78.5645 - val_loss: 15636.7148 - val_mean_absolute_percentage_error: 80.9534
Epoch 44/500
6/6 [==============================] - 1s 149ms/step - loss: 11764.3115 - mean_absolute_percentage_error: 78.7340 - val_loss: 15613.6191 - val_mean_absolute_percentage_error: 80.8933
Epoch 45/500
6/6 [==============================] - 1s 186ms/step - loss: 11676.7383 - mean_absolute_percentage_error: 78.4474 - val_loss: 15590.6426 - val_mean_absolute_percentage_error: 80.8336
Epoch 46/500
6/6 [==============================] - 1s 150ms/step - loss: 11643.9004 - mean_absolute_percentage_error: 78.2703 - val_loss: 15567.4746 - val_mean_absolute_percentage_error: 80.7733
Epoch 47/500
6/6 [==============================] - 1s 151ms/step - loss: 11637.3184 - mean_absolute_percentage_error: 78.2393 - val_loss: 15544.3311 - val_mean_absolute_percentage_error: 80.7130
Epoch 48/500
6/6 [==============================] - 1s 157ms/step - loss: 11696.8955 - mean_absolute_percentage_error: 78.5094 - val_loss: 15521.2158 - val_mean_absolute_percentage_error: 80.6527
Epoch 49/500
6/6 [==============================] - 1s 151ms/step - loss: 11544.6924 - mean_absolute_percentage_error: 77.9471 - val_loss: 15498.1748 - val_mean_absolute_percentage_error: 80.5926
Epoch 50/500
6/6 [==============================] - 1s 164ms/step - loss: 11480.5234 - mean_absolute_percentage_error: 77.7576 - val_loss: 15475.0566 - val_mean_absolute_percentage_error: 80.5322
Epoch 51/500
6/6 [==============================] - 1s 157ms/step - loss: 11588.9775 - mean_absolute_percentage_error: 78.0802 - val_loss: 15452.0879 - val_mean_absolute_percentage_error: 80.4722
Epoch 52/500
6/6 [==============================] - 1s 150ms/step - loss: 11508.5156 - mean_absolute_percentage_error: 77.8389 - val_loss: 15429.1211 - val_mean_absolute_percentage_error: 80.4121
Epoch 53/500
6/6 [==============================] - 1s 153ms/step - loss: 11481.7012 - mean_absolute_percentage_error: 77.6742 - val_loss: 15405.9727 - val_mean_absolute_percentage_error: 80.3516
Epoch 54/500
6/6 [==============================] - 1s 152ms/step - loss: 11407.3555 - mean_absolute_percentage_error: 77.5057 - val_loss: 15382.6904 - val_mean_absolute_percentage_error: 80.2906
Epoch 55/500
6/6 [==============================] - 1s 173ms/step - loss: 11454.3799 - mean_absolute_percentage_error: 77.6334 - val_loss: 15359.3955 - val_mean_absolute_percentage_error: 80.2295
Epoch 56/500
6/6 [==============================] - 1s 152ms/step - loss: 11460.9863 - mean_absolute_percentage_error: 77.6978 - val_loss: 15336.2568 - val_mean_absolute_percentage_error: 80.1688
Epoch 57/500
6/6 [==============================] - 1s 154ms/step - loss: 11346.9609 - mean_absolute_percentage_error: 77.2647 - val_loss: 15313.0977 - val_mean_absolute_percentage_error: 80.1081
Epoch 58/500
6/6 [==============================] - 1s 150ms/step - loss: 11459.9268 - mean_absolute_percentage_error: 77.6276 - val_loss: 15290.1855 - val_mean_absolute_percentage_error: 80.0479
Epoch 59/500
6/6 [==============================] - 1s 152ms/step - loss: 11323.5752 - mean_absolute_percentage_error: 77.1805 - val_loss: 15267.3623 - val_mean_absolute_percentage_error: 79.9879
Epoch 60/500
6/6 [==============================] - 1s 155ms/step - loss: 11274.5439 - mean_absolute_percentage_error: 77.0540 - val_loss: 15244.5293 - val_mean_absolute_percentage_error: 79.9278
Epoch 61/500
6/6 [==============================] - 1s 148ms/step - loss: 11350.4795 - mean_absolute_percentage_error: 77.3073 - val_loss: 15221.6270 - val_mean_absolute_percentage_error: 79.8675
Epoch 62/500
6/6 [==============================] - 1s 150ms/step - loss: 11261.3369 - mean_absolute_percentage_error: 76.9750 - val_loss: 15198.8018 - val_mean_absolute_percentage_error: 79.8074
Epoch 63/500
6/6 [==============================] - 1s 149ms/step - loss: 11167.7734 - mean_absolute_percentage_error: 76.6210 - val_loss: 15175.9092 - val_mean_absolute_percentage_error: 79.7470
Epoch 64/500
6/6 [==============================] - 1s 147ms/step - loss: 11331.9316 - mean_absolute_percentage_error: 77.1913 - val_loss: 15152.8838 - val_mean_absolute_percentage_error: 79.6862
Epoch 65/500
6/6 [==============================] - 1s 149ms/step - loss: 11340.8320 - mean_absolute_percentage_error: 77.2694 - val_loss: 15130.0576 - val_mean_absolute_percentage_error: 79.6260
Epoch 66/500
6/6 [==============================] - 1s 150ms/step - loss: 11254.3340 - mean_absolute_percentage_error: 76.9518 - val_loss: 15107.4707 - val_mean_absolute_percentage_error: 79.5663
Epoch 67/500
6/6 [==============================] - 1s 152ms/step - loss: 11235.8975 - mean_absolute_percentage_error: 76.8683 - val_loss: 15084.9170 - val_mean_absolute_percentage_error: 79.5066
Epoch 68/500
6/6 [==============================] - 1s 174ms/step - loss: 11313.9160 - mean_absolute_percentage_error: 77.1646 - val_loss: 15062.4189 - val_mean_absolute_percentage_error: 79.4471
Epoch 69/500
6/6 [==============================] - 1s 148ms/step - loss: 11151.6025 - mean_absolute_percentage_error: 76.5763 - val_loss: 15040.0615 - val_mean_absolute_percentage_error: 79.3879
Epoch 70/500
6/6 [==============================] - 1s 164ms/step - loss: 11200.5234 - mean_absolute_percentage_error: 76.6802 - val_loss: 15017.7100 - val_mean_absolute_percentage_error: 79.3286
Epoch 71/500
6/6 [==============================] - 1s 166ms/step - loss: 11167.2549 - mean_absolute_percentage_error: 76.6267 - val_loss: 14995.2559 - val_mean_absolute_percentage_error: 79.2691
Epoch 72/500
6/6 [==============================] - 1s 154ms/step - loss: 11188.5498 - mean_absolute_percentage_error: 76.7053 - val_loss: 14972.8369 - val_mean_absolute_percentage_error: 79.2096
Epoch 73/500
6/6 [==============================] - 1s 152ms/step - loss: 11252.2363 - mean_absolute_percentage_error: 76.8778 - val_loss: 14950.5938 - val_mean_absolute_percentage_error: 79.1505
Epoch 74/500
6/6 [==============================] - 1s 152ms/step - loss: 11214.1807 - mean_absolute_percentage_error: 76.8220 - val_loss: 14928.1709 - val_mean_absolute_percentage_error: 79.0909
Epoch 75/500
6/6 [==============================] - 1s 153ms/step - loss: 11022.2012 - mean_absolute_percentage_error: 76.1945 - val_loss: 14905.7080 - val_mean_absolute_percentage_error: 79.0311
Epoch 76/500
6/6 [==============================] - 1s 151ms/step - loss: 11052.8330 - mean_absolute_percentage_error: 76.2154 - val_loss: 14883.0996 - val_mean_absolute_percentage_error: 78.9709
Epoch 77/500
6/6 [==============================] - 1s 153ms/step - loss: 10949.1865 - mean_absolute_percentage_error: 75.8832 - val_loss: 14860.4229 - val_mean_absolute_percentage_error: 78.9105
Epoch 78/500
6/6 [==============================] - 1s 150ms/step - loss: 11028.9609 - mean_absolute_percentage_error: 76.1446 - val_loss: 14837.7500 - val_mean_absolute_percentage_error: 78.8500
Epoch 79/500
6/6 [==============================] - 1s 154ms/step - loss: 11086.8691 - mean_absolute_percentage_error: 76.3585 - val_loss: 14815.1523 - val_mean_absolute_percentage_error: 78.7897
Epoch 80/500
6/6 [==============================] - 1s 152ms/step - loss: 10981.5830 - mean_absolute_percentage_error: 75.9928 - val_loss: 14792.6787 - val_mean_absolute_percentage_error: 78.7297
Epoch 81/500
6/6 [==============================] - 1s 151ms/step - loss: 11106.2402 - mean_absolute_percentage_error: 76.3911 - val_loss: 14770.4424 - val_mean_absolute_percentage_error: 78.6702
Epoch 82/500
6/6 [==============================] - 1s 148ms/step - loss: 11067.1562 - mean_absolute_percentage_error: 76.2873 - val_loss: 14748.3564 - val_mean_absolute_percentage_error: 78.6112
Epoch 83/500
6/6 [==============================] - 1s 150ms/step - loss: 10936.5459 - mean_absolute_percentage_error: 75.8144 - val_loss: 14726.3457 - val_mean_absolute_percentage_error: 78.5522
Epoch 84/500
6/6 [==============================] - 1s 148ms/step - loss: 10897.4697 - mean_absolute_percentage_error: 75.6907 - val_loss: 14704.3896 - val_mean_absolute_percentage_error: 78.4934
Epoch 85/500
6/6 [==============================] - 1s 156ms/step - loss: 10841.8145 - mean_absolute_percentage_error: 75.4940 - val_loss: 14682.3291 - val_mean_absolute_percentage_error: 78.4343
Epoch 86/500
6/6 [==============================] - 1s 154ms/step - loss: 11115.5166 - mean_absolute_percentage_error: 76.4076 - val_loss: 14660.0605 - val_mean_absolute_percentage_error: 78.3746
Epoch 87/500
6/6 [==============================] - 1s 155ms/step - loss: 10887.3252 - mean_absolute_percentage_error: 75.7268 - val_loss: 14638.0684 - val_mean_absolute_percentage_error: 78.3155
Epoch 88/500
6/6 [==============================] - 1s 151ms/step - loss: 10649.9980 - mean_absolute_percentage_error: 74.8046 - val_loss: 14615.9053 - val_mean_absolute_percentage_error: 78.2560
Epoch 89/500
6/6 [==============================] - 1s 154ms/step - loss: 10830.7520 - mean_absolute_percentage_error: 75.5107 - val_loss: 14593.5645 - val_mean_absolute_percentage_error: 78.1959
Epoch 90/500
6/6 [==============================] - 1s 155ms/step - loss: 10817.7764 - mean_absolute_percentage_error: 75.3222 - val_loss: 14571.2500 - val_mean_absolute_percentage_error: 78.1358
Epoch 91/500
6/6 [==============================] - 1s 154ms/step - loss: 10761.7959 - mean_absolute_percentage_error: 75.2788 - val_loss: 14549.0059 - val_mean_absolute_percentage_error: 78.0759
Epoch 92/500
6/6 [==============================] - 1s 153ms/step - loss: 10779.8203 - mean_absolute_percentage_error: 75.2531 - val_loss: 14526.7754 - val_mean_absolute_percentage_error: 78.0160
Epoch 93/500

KeyboardInterrupt:

In [51]:
y_pred = rnn_model.predict(X_test_sc)

In [52]:
y_pred

array([[33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880062],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066],
       [33.880066]], dtype=float32)

In [53]:
y_test

222    148.690002
223    148.639999
224    149.320007
225    148.850006
226    152.570007
227    149.800003
228    148.960007
229    150.020004
230    151.490005
231    150.960007
232    151.279999
233    150.440002
234    150.809998
235    147.919998
236    147.869995
237    149.990005
238    150.000000
239    151.000000
240    153.490005
241    157.869995
242    160.550003
243    161.020004
244    161.410004
245    161.940002
246    156.809998
247    160.240005
248    165.300003
249    164.770004
250    163.759995
251    161.839996
Name: Close, dtype: float64